import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import "../style/globals.scss"
import Header from "@/components/Header/Header"
import Footer from "@/components/Footer/Footer"

const inter = Open_Sans({ subsets: ["latin", "cyrillic"], preload: true })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <Header />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  )
}
